global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  docker:
    exposedByDefault: false
    network: frontend
    allowEmptyServices: true

# ping: {}

log:
  level: ERROR

accessLog:
  filters:
    statusCodes:
      # - "200"
      - "300-599"

api:
  dashboard: false
  debug: false
  insecure: false

entryPoints:
  web:
    address: ":80"
    proxyProtocol:
      trustedIPs:
        - "172.0.0.0/32"
